# Databases Credentials
db.driverName =com.mysql.jdbc.Driver
db.connectionString = jdbc:mysql://localhost:3306/smart
db.username = smart
db.password = smart

#Mailer Credentials
mailer.email = yashdeepkaur20133@gmail.com
mailer.password = bqny jrur ebse sjam